log:
  level: "debug"
  mode:  "dev"

database:
  host: "127.0.0.1"
  port:  5432
  username: "postgres"
  password: "password"
  database: "bot"
  ssl_mode: "disable"

alpr:
  url: "https://api.opencars.app"
  token: "xxx"

bot:
  token: "xxx-xxx"
  url: "http://localhost:3000"

grpc:
  vehicle:
    host: 0.0.0.0
    port: 3003
